# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - presist_to_workspace:
          root: /tmp/test
          paths:
            - output.txt
      - run: echo "hello world" > /tmp/test/output.txt

  print_output_file:
    docker:
      - image: circleci/node:10.16.3  
    steps:
      - attach_workspace:
          at: /tmp/test    
      - run: cat /tmp/test/output.txt

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output